In [ ]:
list11 = [1, 2, [3, 4, [5, 6], 7, 8], 9, 10]

while any(isinstance(i, list) for i in list11):
    list22 = []
    for i in list11:
        if isinstance(i, list):
            list22.extend(i)  # flatten one level
        else:
            list22.append(i)
    list11 = list22  # update for next loop

print(list11)


In [4]:
list11=[1,2,[3,4,[5,6],7,8],9,10]
while any(isinstance(i,list) for i in list11):
    list22=[]
    for i in list11:
        if isinstance(i, list):
            list22.extend(i)
        else:
            list22.append(i)

    list11=list22
print(list22)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
import string

def is_valid_password(password, min_len=8, max_len=16):
    has_upper=any(char.isupper() for char in password)
    has_digit =any(char.isdigit() for char in password)
    has_symbol = any(char in string.punctuation for char in password)
    correct_length = min_len <= len(password) <= max_len

    if not correct_length:
        print(f"👎 Password must be between {min_len} and {max_len} characters.")
    if not has_upper:
        print(f"👎 Password must contain at least one uppercase letter.")
    if not has_digit:
        print(f"👎 Password must contain at least one digit.")
    if not has_symbol:
        print(f"👎 Password must contain at least one special symbol.")

    return all([has_upper, has_digit, has_symbol, correct_length])

password=input("Enter your password:")

if is_valid_password(password):
    print("👍 Password is valid!")
else:
    print("⚠️ Password is invalid. Please try again")

👍 Password is valid!


In [17]:
import string

def is_valid_password(password, min_len=8, max_len=16):
    has_upper= any(char.isupper() for char in password)
    has_digit= any(char.isdigit() for char in password)
    has_symbol= any(char in string.punctuation for char in password)
    correct_length= min_len<= len(password) <= max_len

    if not correct_length:
        print(f"👎 Password must contain between {min_len} and {max_len} characters.")
    if not has_upper:
        print(f"👎 Password must contain at least one uppercase letter.")
    if not has_digit:
        print(f"👎 Password must contain atleast one digit.")
    if not has_symbol:
        print(f"👎 Password must contain at leaast one special symbol.")

    return all([has_symbol, has_digit, has_upper, correct_length])

password=input("Enter yout Password:")


if is_valid_password(password):
    print(f"👍Password is valid")
else:
    print(f"⚠️ Password is invalid")

👎 Password must contain at least one uppercase letter.
⚠️ Password is invalid


In [25]:
import string

def valid_password(password, min_len=8, max_len=16):
    has_upper= any(char.isupper() for char in password )
    has_digit= any(char.isdigit() for char in password)
    has_symbol=  any(char in string.punctuation for char in password)
    correct_len= min_len <= len(password) <= max_len

    if not has_upper:
        print("f Password must contain atleast one uppercase")
    if not has_digit:
        print(f"Password must contain atleast one digit")
    if not has_symbol:
        print(f"Password must contain alteast one symbol.")
    if not correct_len:
        print(f"Password length should between {min_len} and {max_len}")

    return all([has_symbol, has_digit, has_upper, correct_len])
    
password=input("Enter Password:")

if valid_password(password):
    print(f"Password is correct")
else:
    print(f"Password is incorrect")

Password is correct


In [26]:
import string

def is_valid_password(password, min_len=8, max_len=16):
    has_upper=any(char.isupper() for char in password)
    has_digit=any(char.isdigit() for char in password)
    has_symbol=any(char in string.punctuation for char in password)
    correct_len=min_len<= len(password) <= max_len

    if not has_upper:
        print(f"Password must contain at least one uppercase")
    if not has_digit:
        print(f"Password must contain at least one digit")
    if not has_symbol:
        print(f"Password must contain at least one symbol")
    if not correct_len:
        print(f"Password length must be between {min_len} and {max_len}")

    return all([has_digit, has_symbol, has_upper, correct_len])
    
password=input("Enter Password")

if is_valid_password(password):
    print(f"Password is valid")
else:
    print(f"Password is invalid")

Password must contain at least one uppercase
Password is invalid


In [37]:
#find duplicates from list

list1=[1,2,3,1,2,3,4,5,6]
dup=[]
unq_list=set()

for i in list1:
    if i in unq_list:
        dup.append(i)
    else:
        unq_list.add(i)

print(dup)


[1, 2, 3]


In [42]:
#eliminate the word starts with A

names=['Alice','Arron',"bob",'charle']
new_name=[i for i in names if not i.startswith('A')]
print(new_name)

['bob', 'charle']


In [46]:
import numpy as np

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
r=np.rot90(matrix)
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]
